package com.woniu.pojo;
// Generated 2019-12-19 19:49:17 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clazz generated by hbm2java
 */
public class Clazz implements java.io.Serializable {

	private Integer cid;
	private Attendance attendance;
	private User user;
	private String cname;
	private Set<User> students = new HashSet<User>(0);
	private Set<Week> weeks = new HashSet<Week>(0);
	private Set<Phase> phases = new HashSet<Phase>(0);

	public Clazz() {
	}

	public Clazz(Attendance attendance, String cname) {
		this.attendance = attendance;
		this.cname = cname;
	}

	public Clazz(Attendance attendance, User user, String cname, Set students, Set weeks, Set phases) {
		this.attendance = attendance;
		this.user = user;
		this.cname = cname;
		this.students = students;
		this.weeks = weeks;
		this.phases = phases;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public Attendance getAttendance() {
		return this.attendance;
	}

	public void setAttendance(Attendance attendance) {
		this.attendance = attendance;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

	public Set getWeeks() {
		return this.weeks;
	}

	public void setWeeks(Set weeks) {
		this.weeks = weeks;
	}

	public Set getPhases() {
		return this.phases;
	}

	public void setPhases(Set phases) {
		this.phases = phases;
	}

}
