package com.woniu.pojo;
// Generated 2019-12-19 19:49:17 by Hibernate Tools 4.3.5.Final

/**
 * Phase generated by hbm2java
 */
public class Phase implements java.io.Serializable {

	private Integer pid;
	private Clazz clazz;
	private User user;
	private String pname;

	public Phase() {
	}

	public Phase(String pname) {
		this.pname = pname;
	}

	public Phase(Clazz clazz, User user, String pname) {
		this.clazz = clazz;
		this.user = user;
		this.pname = pname;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Clazz getClazz() {
		return this.clazz;
	}

	public void setClazz(Clazz clazz) {
		this.clazz = clazz;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

}
