package com.woniu.pojo;
// Generated 2019-12-19 19:49:17 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer sid;
	private Attendance attendance;
	private Clazz clazz;
	private User user;
	private String sname;
	private String saddress;
	private String sphone;
	private Set<Week> weeks = new HashSet<Week>(0);

	public Student() {
	}

	public Student(Attendance attendance, Clazz clazz, User user, String sname, String saddress, String sphone) {
		this.attendance = attendance;
		this.clazz = clazz;
		this.user = user;
		this.sname = sname;
		this.saddress = saddress;
		this.sphone = sphone;
	}

	public Student(Attendance attendance, Clazz clazz, User user, String sname, String saddress, String sphone,
			Set weeks) {
		this.attendance = attendance;
		this.clazz = clazz;
		this.user = user;
		this.sname = sname;
		this.saddress = saddress;
		this.sphone = sphone;
		this.weeks = weeks;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public Attendance getAttendance() {
		return this.attendance;
	}

	public void setAttendance(Attendance attendance) {
		this.attendance = attendance;
	}

	public Clazz getClazz() {
		return this.clazz;
	}

	public void setClazz(Clazz clazz) {
		this.clazz = clazz;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSaddress() {
		return this.saddress;
	}

	public void setSaddress(String saddress) {
		this.saddress = saddress;
	}

	public String getSphone() {
		return this.sphone;
	}

	public void setSphone(String sphone) {
		this.sphone = sphone;
	}

	public Set getWeeks() {
		return this.weeks;
	}

	public void setWeeks(Set weeks) {
		this.weeks = weeks;
	}

}
