package com.woniu.pojo;
// Generated 2019-12-19 19:49:17 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer uid;
	private Role role;
	private String uname;
	private String upwd;
	private Set<Clazz> clazzs = new HashSet<Clazz>(0);
	private Set<Student> students = new HashSet<Student>(0);
	private Set<Phase> phases = new HashSet<Phase>(0);

	public User() {
	}

	public User(String uname, String upwd) {
		this.uname = uname;
		this.upwd = upwd;
	}

	public User(Role role, String uname, String upwd, Set clazzs, Set students, Set phases) {
		this.role = role;
		this.uname = uname;
		this.upwd = upwd;
		this.clazzs = clazzs;
		this.students = students;
		this.phases = phases;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpwd() {
		return this.upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	public Set getClazzs() {
		return this.clazzs;
	}

	public void setClazzs(Set clazzs) {
		this.clazzs = clazzs;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

	public Set getPhases() {
		return this.phases;
	}

	public void setPhases(Set phases) {
		this.phases = phases;
	}

	@Override
	public String toString() {
		return "User [uid=" + uid + ", role=" + role + ", uname=" + uname + ", upwd=" + upwd + ", clazzs=" + clazzs
				+ ", students=" + students + ", phases=" + phases + "]";
	}

}
