package com.woniu.pojo;
// Generated 2019-12-19 19:49:17 by Hibernate Tools 4.3.5.Final

/**
 * Week generated by hbm2java
 */
public class Week implements java.io.Serializable {

	private Integer wid;
	private Clazz clazz;
	private Student student;
	private float wscore;

	public Week() {
	}

	public Week(Student student, float wscore) {
		this.student = student;
		this.wscore = wscore;
	}

	public Week(Clazz clazz, Student student, float wscore) {
		this.clazz = clazz;
		this.student = student;
		this.wscore = wscore;
	}

	public Integer getWid() {
		return this.wid;
	}

	public void setWid(Integer wid) {
		this.wid = wid;
	}

	public Clazz getClazz() {
		return this.clazz;
	}

	public void setClazz(Clazz clazz) {
		this.clazz = clazz;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public float getWscore() {
		return this.wscore;
	}

	public void setWscore(float wscore) {
		this.wscore = wscore;
	}

}
